version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: output/logs/usaspending.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: output/logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

root:
  level: DEBUG  # Changed from INFO to DEBUG
  handlers: [console, file, debug_file]