version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: output/logs/usaspending.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: output/logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

  critical_file:
    class: logging.handlers.RotatingFileHandler
    level: CRITICAL
    formatter: standard
    filename: output/logs/critical.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: output/logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

root:
  level: DEBUG  # Base level - will catch everything except TRACE which maps to DEBUG anyway
  handlers: [console, file, debug_file, critical_file, error_file]