version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/usaspending.log
    encoding: utf8

  debug_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug.log
    encoding: utf8

loggers:
  usaspending:
    level: INFO
    handlers: [console, file, debug_file]
    propagate: false

root:
  level: INFO
  handlers: [console]